# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d0255cd895bd58abbe5b3cc8dfe70915e018f362f702bf559a69d74f8443111202a009df7c0d7f7e52b57e6b0f8398db76a4d2340206bb075d3cf4540abf173

test:
  secret_key_base: c61ec77d78a6c0655ffcbb960710ee61fd8243362d96b3721f237c0ff1e20d3ea889dd98884c3a5f6708d88fa8adee1e185dfe7ee1788196eecadf64f7b6f05e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
